### PR TITLE
Proposal for new shape: Image (WIP)

### PR DESCRIPTION
**Pull request by Landerson352**
##### To-Dos:
- [X] Create Image shape.
- [X] Load images into DOM as the Image shapes are created.
- [X] Render image source on canvas.
- [X] Handle `w` and `h` in props, as overrides on the source image size.
- [ ] Handle image-load latency. For example, re-render canvas when all images have completed loading.
- [ ] Clean up images in DOM on reload. Otherwise they duplicate on every re-compile.
- [ ] Test with parenting, phasing and other props.

## Image
The image shape takes a `url` property and displays the corresponding image on the canvas, with the image's center at the x/y position.

image

### CODE REVIEW

**Comment by bit101** [comment]
I've actually had this written and functioning for weeks. But due to security issues, the browser will not allow you to getImageData from a canvas that has a cross domain image drawn to it.

**Comment by Landerson352** [comment]
Ah, you're right! Bummer. So it could work, but only for locally stored images?

**Comment by bit101** [comment]
It has to  run off a server with the image on the same domain or cross
platform rules set up just right.

**Comment by bit101** [comment]
I'm now working on an executable version of GLC using electron. I just gave my image module a try in that, and as I suspected, it works fine. As the code I already wrote is very similar to what you made here, I'm going to close this pull request out and will eventually push what I already have.

**Comment by Landerson352** [comment]
Wow, that sounds incredible! I look forward to seeing what you've come up with.

**Comment by bit101** [comment]
In the renderlist, I create the image and add it as a property.

	function addImage(props) {
		var image = document.createElement("img");
		image.src = props.url;
		props.image = image;
		return add(Shape.create(Image, props));
	}

There's no need to add it to the DOM, so no need to clean that up. Here's my image module

define(function() {
	
	return {
		draw: function(context, t) {
			var image = this.getObject("image", t, null),
				x = this.getNumber("x", t, 100),
				y = this.getNumber("y", t, 100),
				w = this.getNumber("w", t, -1),
				h = this.getNumber("h", t, -1),
			    rotation = this.getNumber("rotation", t, 0) * Math.PI / 180,
			    drawFromCenter = this.getBool("drawFromCenter", t, true),
			    smooth = this.getBool("smooth", t, true);


		    context.translate(x, y);
		    context.rotate(rotation);
		    if(w === -1) {
		    	w = image.width;
		    }
		    if(h === -1) {
		    	h = image.height;
		    }
		    context.imageSmoothingEnabled = smooth;
		    context.mozImageSmoothingEnabled = smooth;
			context.webkitImageSmoothingEnabled = smooth;
 			context.msImageSmoothingEnabled = smooth
		    this.setShadowParams(context, t);
		    if(drawFromCenter) {
			    context.drawImage(image, -w / 2, -h / 2, w, h);
			}
			else {
			    context.drawImage(image, 0, 0, w, h);
			}
		}
	}
});

Really pretty simple. The only thing I'm not handling is the load time. It's not a big issue if the sketch is animating. The image will be drawn every frame. It will be empty at first, but still be drawn. When it loads, then the actual bitmap is drawn. The only issue with that will be if the sketch isn't set up to loop at first. I guess I can trigger a render when it does load, if the scheduler is not running.

**Pull request closed without merging**
