### PR TITLE
Update to recursive copy when building documentation

### PR DESCRIPTION
**Pull request by Landerson352**
Perhaps Linux/Unix are more forgiving, but on my system (OSX), the flags used on the `cp` command must be placed before the filepath arguments. The format I've used here is how it appears in the OSX handbook, and in a couple of Linux/UNIX sites I've found. So hopefully it is compatible with all systems, but I don't have a way to test it on-hand.

### CODE REVIEW

**Comment by bit101** [comment]
I'm on windows using git bash (basically cygwin) mainly, though I have multiple machines of each type on hand. Need to be better about testing on various platforms.

**Comment by Landerson352** [comment]
Ah, interesting. I hadn't even considered Git bash on Windows. I saw you dropped the `.bat` file so that makes sense. Well, again, I might be the only other person on the planet trying to compile your code, so don't feel too bad about it. ;)

**Comment by bit101** [comment]
Yeah, I was using the bat file, but all the commands in it were actually
*nix based anyway, so I dropped it in favor of the .sh script. Eventually
I'll probably move it over to grunt or something.

On Fri, Jan 1, 2016 at 9:11 PM, Lincoln Anderson <notifications@github.com>
wrote:

> Ah, interesting. I hadn't even considered Git bash on Windows. I saw you
> dropped the .bat file so that makes sense. Well, again, I might be the
> only other person on the planet trying to compile your code, so don't feel
> too bad about it. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bit101/gifloopcoder/pull/14#issuecomment-168357369>.
>



-- 
---| Keith Peters
---| kp@bit-101.com
---| www.bit-101.com

**Comment by Landerson352** [comment]
Neat. If you consider using Gulp, I have some experience and would be happy to lend a hand.

**Pull request merged**
